name: test_starter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_starter:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Secrets
        run: |
          echo "üîç Checking for required secrets..."
          if [ -z "${{ secrets.PROJECT_NAME }}" ]; then
            echo "‚ùå PROJECT_NAME is not set! Please add it to your repository secrets."
            exit 1
          else
            echo "‚úÖ PROJECT_NAME is set."
            echo "Project Name: ${{ secrets.PROJECT_NAME }}"
          fi
